channels:
  - defaults
  - conda-forge
  - saturncloud
dependencies:
  - nodejs
  - python
  - ipywidgets
  - jupyterlab-git
  - jupyterlab=2.2.9
  - nbconvert
  - notebook
  - jupyter-server-proxy
  - dask-core
  - distributed
  - dask-labextension
  - yarl
  - pyviz_comms
  - jupyterlab_code_formatter
  - black
  - isort
  - tornado
  - nbdime
  - voila
