name: saturn
channels:
- nodefaults
- conda-forge
dependencies:
- ipykernel
- ipywidgets
- matplotlib
- numpy=1.19.5
- pandas
- pip
- pyarrow
- python-graphviz
- s3fs
- scikit-learn
- scipy
- python=3.8
- pip:
  - tensorflow==2.4.1
