name: saturn
channels:
- https://conda.saturncloud.io/pkgs
- nvidia
- rapidsai
- pytorch
- numba
- defaults
- conda-forge
- saturncloud
dependencies:
- blas=*=mkl
- bokeh
- cvxpy
- dash
- dash-bootstrap-components
- dash-core-components
- dash-daq
- dash-html-components
- dash-renderer
- dash-table
- dask-ml
- dask=2.30.0
- distributed=2.30.1
- fastparquet
- gensim
- geopandas
- graphviz
- h5py
- ipykernel
- ipywidgets
- llvmlite
- matplotlib
- nltk
- numba
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- pytorch
- rapids
- s3fs
- scikit-learn
- scipy
- snowflake-connector-python==2.3.2
- snowflake-sqlalchemy
- tensorboard
- tensorflow-base
- tensorflow-estimator
- tensorflow
- torchvision
- voila
- wordcloud
- xgboost=1.3.0dev.rapidsai0.17=cuda10.1py37_0
- pip:
  - dask-saturn==0.2.2
