name: saturn
channels:
- https://conda.saturncloud.io/pkgs
- nvidia
- rapidsai
- pytorch
- numba
- defaults
- conda-forge
- saturncloud
dependencies:
- blas=*=mkl
- bokeh
- cvxpy
- dash
- dash-bootstrap-components
- dash-core-components
- dash-daq
- dash-html-components
- dash-renderer
- dash-table
- dask-ml
- dask-saturn=0.1.1
- dask-xgboost
- dask=2.20.0
- distributed=2.20.0
- fastparquet
- gensim
- geopandas
- graphviz
- h5py
- ipykernel
- ipywidgets
- llvmlite=0.32.1
- matplotlib
- nltk
- numba=0.49.1
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
- rapids=0.14.1=cuda10.1_py37_0
- s3fs
- scikit-learn
- scipy
- snowflake-connector-python
- snowflake-sqlalchemy
- tensorboard=2.1.0
- tensorflow-base=2.1.0=gpu_py37h6c5654b_0
- tensorflow-estimator=2.1.0
- tensorflow=2.1.0=gpu_py37h7a4bb67_0
- torchvision=0.5.0=py37_cu101
- voila
- wordcloud
- xgboost
