name: saturn
channels:
- https://conda.saturncloud.io/pkgs
- nvidia
- rapidsai
- pytorch
- numba
- defaults
- conda-forge
- saturncloud
dependencies:
- blas=*=mkl
- bokeh
- cvxpy
- dash
- dash-bootstrap-components
- dash-core-components
- dash-daq
- dash-html-components
- dash-renderer
- dash-table
- dask-ml
- dask=2.30.0
- distributed=2.30.1
- fastparquet
- gensim
- geopandas
- graphviz
- h5py
- ipykernel
- ipywidgets
- llvmlite
- matplotlib
- nltk
- numba
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- pytorch=1.7.0=py3.7_cuda10.1.243_cudnn7.6.3_0
- rapids=0.17.0=cuda10.1_py37_g180f433_165
- s3fs
- scikit-learn
- scipy
- snowflake-connector-python==2.1.1
- snowflake-sqlalchemy
- tensorboard=2.2.1
- tensorflow-estimator=2.2.0
- tensorflow==2.2.0=gpu_py37h1a511ff_0
- torchvision=0.8.1=py37_cu101
- voila
- wordcloud
- xgboost=1.3.0dev.rapidsai0.17=cuda10.1py37_0
- pip:
  - dask-saturn==0.2.2
