name: saturn
channels:
- https://conda.saturncloud.io/pkgs
- rapidsai/label/cuda10.0
- nvidia
- rapidsai
- pytorch
- numba
- defaults
- conda-forge
dependencies:
#- blas=*=mkl
- nodejs=10.13.0
- python=3.7
- numpy
- pandas
- ipywidgets=7.2*
- numexpr
- matplotlib
- scipy
- seaborn
- scikit-learn
- scikit-image
- sympy
- cython
- patsy
- statsmodels
- cloudpickle
- dill
- bokeh
- sqlalchemy
- hdf5
- h5py
- vincent
- beautifulsoup4
- protobuf
- xlrd
- ipykernel
- dask
- s3fs
- dash
- dash-bootstrap-components
- dash-core-components
- dash-daq
- dash-html-components
- dash-renderer
- dash-table
- pip
- s3fs
- nltk
- gensim
- wordcloud
- pytorch=1.1.0=py3.7_cuda10.0.130_cudnn7.5.1_0
- torchvision=0.3.0=py37_cu10.0.130_1
- tensorboard=2.0.0
- tensorflow-gpu=2.0.0
- rapids=0.12
- rapids-xgboost=0.12
- cvxpy
- cudf
- cuml
- cugraph
- xgboost
- dask-cuda
- dask-cudf
- dask-cuml
- dask-xgboost
- cudatoolkit=10.0
- python-louvain
- networkx
- numba
- pyarrow
- snowflake-connector-python
- snowflake-sqlalchemy
- pip:
  - tweepy
  - graphistry
  - mockito
  - graphviz
  - kaggle