name: saturn
channels:
- nvidia
- rapidsai
- defaults
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- dask-ml
- dask=2.30.0
- distributed=2.30.1
- graphviz
- ipykernel
- ipywidgets
- numba
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- rapids=0.17.0=cuda10.1_py37_g180f433_165
- s3fs
- scikit-learn
- scipy
- xgboost=1.3.0dev.rapidsai0.17=cuda10.1py37_0
- pip:
  - dask-saturn>=0.2.2
  - prefect-saturn>=0.4.0
  - snowflake-connector-python
