channels:
    - conda-forge
dependencies:
    - black
    - ipywidgets
    - isort
    - jupyter-server-proxy
    - jupyterlab-nvdashboard
    - jupyterlab-git
    - jupyterlab=3.6.3
    - nbconvert
    - nbdime
    - nodejs
    - notebook
    - pip
    - python=3.10
    - tornado
    - yarl
    - pip:
          - jupyterlab_code_formatter
          - jupyterlab_execute_time
          - jupyterlab_widgets
          - nbclassic>=0.2.8
          - theme-darcula
