name: saturn
channels:
    - nodefaults
    - conda-forge
dependencies:
    - blas=*=mkl
    - bokeh
    - dask-ml
    - dask
    - ipykernel
    - ipywidget
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyarrow
    - python=3.11
    - python-graphviz
    - s3fs
    - scikit-learn
    - scipy
    - setuptools
    - voila
    - xgboost
    - pip:
          - dask-saturn
          - snowflake-connector-python
          - saturn-client
          - saturnfs
