name: saturn
channels:
    - nodefaults
    - conda-forge
dependencies:
    - blas=2.114=mkl
    - bokeh=2.4.3
    - dask-ml=2022.1.22
    - dask=2022.5.0
    - ipykernel=6.13.0
    - ipywidgets=7.7.0
    - matplotlib=3.5.2
    - numpy=1.21.6
    - pandas=1.4.2
    - pip
    - prefect=0.15.13
    - pyarrow=6.0.1
    - python=3.9
    - python-graphviz=0.20
    - s3fs=2022.3.0
    - scikit-learn=1.0.2
    - scipy=1.8.0
    - setuptools<60.0
    - voila=0.3.5
    - xgboost=1.5.1
    - pip:
          - dask-saturn>=0.4.1
          - prefect-saturn>=0.6.0
          - snowflake-connector-python==2.7.7
