channels:
  - defaults
  - conda-forge
dependencies:
  - nodejs
  - python
  - ipywidgets
  - jupyterlab-git
  - jupyterlab=3.2.2
  - nbconvert
  - notebook
  - jupyter-server-proxy
  - dask-core
  - distributed
  - yarl
  - pyviz_comms
  - black
  - isort
  - tornado=6
  - jupyterlab-nvdashboard
  - nbdime
  - voila
  - pip
  - setuptools<60.0
  - pip:
    - nbclassic>=0.2.8
    - jupyterlab_execute_time
    - jupyterlab_code_formatter
    - jupyter_bokeh
    - jupyterlab_widgets
    - theme-darcula
