name: dask-saturn
channels:
  - saturncloud
  - https://conda.saturncloud.io/pkgs
  - conda-forge
dependencies:
  - python=3.7
  - dask=2.11.0
  - distributed
  - sutils=0.5.1
  - kubernetes
  - dask-kubernetes
  - python-kubernetes
  - tornado
