name: saturn
channels:
    - conda-forge
    - nodefaults
    - rapidsai
dependencies:
    - blas=*=mkl
    - bokeh
    - dask
    - dask-cuda
    - fsspec
    - ipykernel
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - pip
    - prefect
    - pyarrow
    - python
    - python-graphviz
    - s3fs
    - setuptools
    - tensorboard
    - voila
    - pynvml
    - pip:
      - dask-saturn==0.4.4
      - saturn-client
      - saturnfs
      - snowflake-connector-python
      - tensorflow[and-cuda]
      - keras
