name: saturn
channels:
    - conda-forge
    - nodefaults
    - rapidsai
dependencies:
    - blas=*=mkl
    - bokeh
    - cudnn
    - cudatoolkit=11.2
    - dask
    - dask-cuda==22.04
    - fsspec
    - ipykernel
    - ipywidgets
    - keras
    - matplotlib
    - numpy
    - pandas
    - pip
    - prefect<1.0.0
    - pyarrow<6.1.0,>=6.0.0
    - python=3.9
    - python-graphviz
    - s3fs>=2021.08.0
    - setuptools<60.0
    - tensorboard
    - voila
    - pip:
        - tensorflow
        - dask-saturn>=0.4.1
        - prefect-saturn>=0.6.0
        - snowflake-connector-python

