name: saturn
channels:
    - conda-forge
    - nodefaults
    - rapidsai
dependencies:
    - blas=2.114=mkl
    - bokeh=2.4.3
    - cudatoolkit=11.2
    - dask=2022.3.0
    - dask-cuda=22.04
    - fsspec=2022.3.0
    - ipykernel=6.13.0
    - ipywidgets=7.7.0
    - keras=2.7.0
    - matplotlib=3.5.2
    - numpy=1.21.6
    - pandas=1.4.2
    - pip
    - prefect=0.15.13
    - pyarrow=6.0.1
    - python=3.9
    - python-graphviz=0.20
    - s3fs=2022.3.0
    - setuptools<60.0
    - tensorboard=2.6.0
    - tensorflow-estimator=2.7.0
    - tensorflow-gpu=2.7.0=cuda112py39*
    - voila=0.3.5
    - pip:
          - dask-saturn>=0.4.1
          - prefect-saturn>=0.6.0
          - snowflake-connector-python==2.7.7
