name: saturn
channels:
    - conda-forge
    - nodefaults
    - rapidsai
dependencies:
    - blas=2.114=mkl
    - bokeh
    - dask
    - dask-cuda
    - fsspec
    - ipykernel=
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - pip
    - prefect
    - pyarrow
    - python
    - python-graphviz
    - s3fs
    - setuptools
    - tensorboard
    - voila
    - pynvml
    - pip:
      - dask-saturn>=0.4.1
      - prefect-saturn>=0.6.0
      - snowflake-connector-python
      - tensorflow[and-cuda]
      - keras
