name: saturn
channels:
- nvidia
- rapidsai
- nodefaults
- conda-forge
dependencies:
- blas=2.112=mkl
- blazingsql=21.06.00=cuda_11.2_py37_g95ff589f8_0
- bokeh=2.2.3
- click>=7.1.2,<8.0.0
- cvxpy=1.1.18
- dask-ml=2021.11.30
- dask=2021.4.1
- distributed=2021.4.1
- dask-cudf=21.06.01=py37_g101fc0fda4_2 
- ipykernel=6.7.0
- ipywidgets=7.6.5
- matplotlib=3.5.1
- numba=0.54.1
- numpy=1.20.3
- pandas=1.2.5
- pip=21.3.1
- prefect=0.15.12
- pyarrow=1.0.1
- python=3.7.12
- python-graphviz=0.19.1
- rapids-blazing=21.06.01=cuda11.2_py37_gecaf371_431
- s3fs=2022.1.0
- scikit-learn=1.0.2
- scipy=1.7.3
- setuptools<60.0
- voila=0.3.0
- xgboost=1.4.2dev.rapidsai21.06=cuda11.2py37_0
- pip:
  - dask-saturn>=0.4.0
  - prefect-saturn>=0.5.1
  - snowflake-connector-python==2.7.2
