name: saturn
channels:
- nvidia
- rapidsai
- nodefaults
- conda-forge
dependencies:
- blas=2.113=mkl
- blazingsql=21.6.0
- bokeh=2.2.3
- click>=7.1.2,<8.0.0
- cudf=21.06.01=cuda_11.2_py37_g101fc0fda4_2
- cvxpy=1.1.18
- dask-ml=2022.1.22
- dask=2021.4.1
- dask-cudf=21.06.01=py37_g101fc0fda4_2
- ipykernel=6.9.1
- ipywidgets=7.6.5
- matplotlib=3.5.1
- numba=0.55.1
- numpy=1.21.5
- pandas=1.2.5
- pip=22.0.3
- prefect=0.15.13
- pyarrow
- python=3.7
- python-graphviz=0.19.1
- rapids=21.06.01
- s3fs=2022.2.0
- scikit-learn=1.0.2
- scipy=1.7.3
- setuptools<60.0
- voila=0.3.2
- xgboost=1.4.2dev.rapidsai21.06
- pip:
  - dask-saturn>=0.4.1
  - prefect-saturn>=0.6.0
  - snowflake-connector-python==2.7.4
