name: saturn
channels:
- nvidia
- rapidsai
- nodefaults
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- cvxpy
- dask-ml
- dask=2021.4.0
- distributed=2021.4.0
- ipykernel
- ipywidgets
- matplotlib
- numba
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- python-graphviz
- rapids-blazing=0.19.0=cuda10.1_py37_ga03647d_299
- s3fs
- scikit-learn
- scipy
- voila
- xgboost=1.4.0dev.rapidsai0.19=cuda10.1py37_0
- pip:
  - dask-saturn>=0.2.3
  - prefect-saturn>=0.5.0
  - snowflake-connector-python
