name: saturn
channels:
- nvidia
- rapidsai
- nodefaults
- conda-forge
dependencies:
- blas=*=mkl
- blazingsql=21.10.00=cuda_11.2_py37_g2a4a99cc8_0
- bokeh
- cvxpy
- dask-ml
- dask=2021.9.1
- distributed=2021.9.1
- dask-cudf=21.10.00=py37_g072fd862cc_0
- ipykernel
- ipywidgets
- matplotlib
- numba
- numpy
- pandas
- pip
- prefect
- pyarrow=5.0.0
- python
- python-graphviz
- rapids-blazing=21.10.00=cuda11.2_py37_ge66f011_114
- s3fs
- scikit-learn
- scipy
- voila
- xgboost=1.4.2dev.rapidsai21.10=cuda11.2py37_0
- pip:
  - dask-saturn>=0.4.0
  - prefect-saturn>=0.5.1
  - snowflake-connector-python
  