name: saturn
channels:
- nvidia
- rapidsai
- nodefaults
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- cvxpy
- dask-ml
- dask=2.30.0
- distributed=2.30.1
- ipykernel
- ipywidgets
- matplotlib
- numba
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- python-graphviz
- rapids=0.17.0=cuda10.1_py37_g180f433_165
- s3fs
- scikit-learn
- scipy
- voila
- xgboost=1.3.0dev.rapidsai0.17=cuda10.1py37_0
- pip:
  - dask-saturn>=0.2.2
  - git+https://github.com/saturncloud/prefect-saturn.git@926c4fe63e22545abd5ba22dd715cf20db828e42
  - snowflake-connector-python
