name: saturn
channels:
- nvidia
- rapidsai
- numba
- defaults
- saturncloud
dependencies:
- blas=*=mkl
- bokeh
- dask-saturn
- dask
- distributed
- matplotlib
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- s3fs
- voila
- ipykernel
- ipywidgets
- dask-ml
- rapids=0.15.1=cuda10.1_py37_gc1db54b_5
- dask-xgboost
- pip:
  - snowflake-connector-python
  - prefect-saturn
