name: saturn
channels:
- nvidia
- rapidsai
- nodefaults
- conda-forge
dependencies:
- blas=2.114=mkl
- blazingsql=21.10.00=cuda_11.2_py38_g2a4a99cc8_0
- bokeh=2.4.0
- cvxpy=1.2.0
- dask-ml=2022.1.22
- dask=2021.9.1
- dask-cudf=21.10.00=py38_g072fd862cc_0
- ipykernel=6.13.0
- ipywidgets=7.7.0
- matplotlib=3.5.1
- numba=0.55.1
- numpy=1.21.6
- pandas=1.3.5
- pip=22.0.4
- prefect=0.15.13
- pyarrow=5.0.0
- python=3.8
- python-graphviz=0.20
- rapids-blazing=21.10.00=cuda11.2_py38_ge66f011_114
- s3fs=2022.3.0
- scikit-learn=1.0.2
- scipy=1.8.0
- setuptools<60.0
- voila=0.3.5
- xgboost=1.4.2dev.rapidsai21.10=cuda11.2py38_0
- pip:
  - dask-saturn>=0.4.1
  - prefect-saturn>=0.6.0
  - snowflake-connector-python==2.7.6
