name: saturn
channels:
- nvidia
- rapidsai
- nodefaults
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- cvxpy
- dask-ml
- dask=2021.7.2
- distributed=2021.7.2
- ipykernel
- ipywidgets
- matplotlib
- numba
- numpy
- pandas
- pip
- prefect
- pyarrow
- python
- python-graphviz
- rapids-blazing=21.06.01=cuda11.2_py37_gecaf371_431
- s3fs
- scikit-learn
- scipy
- voila
- xgboost=1.4.2dev.rapidsai21.06=cuda11.2py37_0
- pip:
  - dask-saturn>=0.3.0
  - prefect-saturn>=0.5.1
  - snowflake-connector-python
