channels:
  - defaults
  - conda-forge
dependencies:
  - nodejs
  - ipywidgets
  - jupyterlab-git
  - jupyterlab=3.4.7
  - jupyter-server-proxy
  - nbconvert
  - nbdime
  - notebook
  - pip
  - setuptools<60.0
  - tornado
  - yarl
  - pip:
    - nbclassic>=0.2.8
    - jupyterlab_execute_time
    - jupyterlab_widgets
    - webio_jupyter_extension
