name: saturn
channels:
    - nvidia
    - rapidsai
    - nodefaults
    - conda-forge
dependencies:
    - bokeh
    - cuda-version=12.0
    - cvxpy
    - dask-ml
    - dask-sql
    - dask
    - ipykernel
    - ipywidgets
    - matplotlib
    - numba
    - numpy
    - pandas
    - pip
    - prefect
    - pyarrow
    - python-graphviz
    - python
    - rapids
    - s3fs
    - scikit-learn
    - scipy
    - setuptools
    - pip:
          - dask-saturn
          - saturn-client
          - saturnfs
          - snowflake-connector-python
