name: saturn
channels:
    - nvidia
    - rapidsai
    - nodefaults
    - conda-forge
dependencies:
    - bokeh
    - cudatoolkit
    - cvxpy
    - dask-ml
    - dask-sql
    - dask
    - ipykernel
    - ipywidgets
    - matplotlib
    - numba
    - numpy
    - pandas
    - pip
    - prefect
    - pyarrow
    - python-graphviz
    - python=3.9
    - rapids=22.06
    - s3fs
    - scikit-learn
    - scipy
    - setuptools
    - pip:
          - dask-saturn>=0.4.1
          - prefect-saturn>=0.6.0
          - snowflake-connector-python
