name: saturn
channels:
    - nvidia
    - rapidsai
    - nodefaults
    - conda-forge
dependencies:
    - blas=*=mkl
    - bokeh
    - cudatoolkit=11.2
    - cvxpy
    - dask-ml
    - dask
    - dask-sql
    - ipykernel
    - ipywidgets
    - matplotlib
    - numba
    - numpy
    - pandas
    - pip
    - prefect<1.0.0
    - pyarrow<6.1.0,>=6.0.0
    - python=3.9
    - python-graphviz
    - s3fs>=2021.08.0
    - scikit-learn
    - scipy
    - setuptools<60.0
    - rapids=22.04
    - pip:
          - dask-saturn>=0.4.1
          - prefect-saturn>=0.6.0
          - snowflake-connector-python
