name: saturn
channels:
- pytorch
- fastai
- rapidsai
- defaults
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- dask=2.30.0
- dask-cuda=0.17.*
- distributed=2.30.1
- fastai
- fsspec>=0.8.5
- ipykernel
- ipywidgets
- matplotlib
- numpy
- pandas
- pillow
- pip
- prefect
- py-opencv
- pyarrow
- python=3.7
- python-graphviz
- pytorch=1.7.0=py3.7_cuda10.1.243_cudnn7.6.3_0
- s3fs
- tensorboard=2.2.1
- torchvision=0.8.1=py37_cu101
- voila
- pip:
  - dask-saturn>=0.2.2
  - git+https://github.com/saturncloud/prefect-saturn.git@926c4fe63e22545abd5ba22dd715cf20db828e42
  - snowflake-connector-python
