name: saturn
channels:
- pytorch
- fastai
- rapidsai
- defaults
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- dask=2021.07
- distributed=2021.07
- dask-cuda=0.19
- fastai
- fsspec>=0.8.5
- ipykernel
- ipywidgets
- matplotlib
- numpy
- pandas
- pillow
- pip
- prefect
- py-opencv=4.5.2=py39hef51801_0
- pyarrow
- python=3.9
- python-graphviz
- pytorch=1.9.1=py3.9_cuda11.1_cudnn8.0.5_0
- s3fs
- tensorboard
- torchvision
- pip:
  - dask-saturn>=0.3.0
  - prefect-saturn>=0.5.1
  - snowflake-connector-python
