name: saturn
channels:
- https://conda.saturncloud.io/pkgs
- pytorch
- numba
- defaults
- conda-forge
- saturncloud
dependencies:
- blas=*=mkl
- bokeh
- cvxpy
- dask-saturn
- dask=2.30.0
- distributed=2.30.0
- ipykernel
- ipywidgets
- matplotlib
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- pytorch=py3.7_cuda10.1.243_cudnn7.6.3_0
- s3fs
- scikit-learn
- scipy
- snowflake-connector-python
- torchvision=0.5.0=py37_cu101
- voila
- tensorboard=2.2.0
