name: saturn
channels:
- pytorch
- fastai
- rapidsai
- defaults
- conda-forge
dependencies:
- blas=1.0=mkl
- bokeh=2.4.2
- dask=2021.7.0
- dask-cuda=21.8
- fastai=1.0.61
- fsspec=2022.2.0
- ipykernel=6.9.1
- ipywidgets=7.6.5
- matplotlib=3.5.1
- numpy=1.21.5
- pandas=1.4.2
- pillow=9.0.1
- pip=21.2.4
- prefect=0.15.13
- py-opencv=4.5.2=py39hef51801_0
- pyarrow=3.0.0
- python=3.9
- python-graphviz=0.16
- pytorch=1.9.1=py3.9_cuda11.1_cudnn8.0.5_0
- s3fs=0.6.0
- setuptools<60.0
- tensorboard=2.6.0
- torchvision=0.2.2
- pip:
  - dask-saturn>=0.4.1
  - prefect-saturn>=0.6.0
  - snowflake-connector-python==2.7.6
