name: saturn
channels:
- pytorch
- defaults
- conda-forge
- saturncloud
dependencies:
- blas=*=mkl
- bokeh
- dask-saturn
- dask
- distributed
- matplotlib
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- s3fs
- voila
- ipykernel
- ipywidgets
- pytorch=py3.7_cuda10.1.243_cudnn7.6.3_0
- torchvision=0.5.0=py37_cu101
- tensorboard=2.2.0
- py-opencv
- pillow
- pip:
  - snowflake-connector-python
  - prefect-saturn
