name: saturn
channels:
- pytorch
- fastai
- rapidsai
- defaults
- conda-forge
dependencies:
- blas=1.0=mkl
- bokeh=2.4.2
- click>=7.1.2,<8.0.5
- dask=2021.07
- distributed=2021.07
- dask-cuda=21.8.0
- fastai=1.0.61
- fsspec=2021.10.1
- ipykernel=6.4.1
- ipywidgets=7.6.5
- matplotlib=3.5.0
- numpy=1.21.2
- pandas=1.3.5
- pillow=8.4.0
- pip=21.2.4
- prefect=0.15.12
- py-opencv=4.5.2=py39hef51801_0
- pyarrow=3.0.0
- python=3.9.7
- python-graphviz=0.16
- pytorch=1.9.1=py3.9_cuda11.1_cudnn8.0.5_0
- s3fs=0.6.0
- setuptools<60.0
- tensorboard=2.6.0
- torchvision=0.2.2
- pip:
  - dask-saturn>=0.4.0
  - prefect-saturn>=0.5.1
  - snowflake-connector-python==2.7.2
