channels:
  - defaults
  - conda-forge
  - https://conda.saturncloud.io/pkgs
  - saturncloud
dependencies:
  - nodejs=11
  - python=3.7
  - ipywidgets
  - jupyterlab=2.0.1
  - nbconvert
  - notebook
  - jupyter-server-proxy
  - tornado=6
  - jupyter_saturn=${JUPYTER_SATURN_VERSION}
  - nbdime
  - pyyaml
  - voila
