channels:
  - defaults
  - conda-forge
  - https://conda.saturncloud.io/pkgs
  - saturncloud
dependencies:
  - nodejs=11
  - python=3.7
  - ipywidgets
  - jupyterlab=2.2.0
  - nbconvert
  - notebook
  - jupyter-server-proxy
  - dask-labextension=3.0.0
  - yarl=1.4.2
  - pyviz_comms
  - jupyterlab_code_formatter=1.3.8
  - black
  - isort
  - tornado=6
  - jupyter_saturn=${JUPYTER_SATURN_VERSION}
  - nbdime
  - pyyaml
  - voila
