name: saturn
channels:
- nodefaults
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- cartopy
- dask-ml
- dask=2.30.0
- datashader
- descartes
- distributed=2.30.1
- geopandas
- geoviews
- hvplot
- ipykernel
- ipywidgets
- iris
- matplotlib
- netcdf4
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- python-graphviz
- rasterio
- s3fs
- scipy
- voila
- xarray
- zarr
- pip:
  - dask-saturn>=0.2.2
  - prefect-saturn>=0.4.0
  - snowflake-connector-python
