name: saturn
channels:
- conda-forge
- defaults
dependencies:
- blas=*=mkl
- bokeh
- cartopy
- dask-ml
- dask==2.30.0
- datashader
- distributed==2.30.1
- geopandas
- graphviz
- hvplot
- ipykernel
- ipywidgets
- iris
- matplotlib
- netcdf4
- numpy
- pandas=1.1.0
- panel
- pip
- prefect
- pyarrow
- python=3.7
- rasterio
- s3fs
- scipy
- voila
- xarray
- zarr
- pip:
  - dask-saturn>=0.2.2
  - prefect-saturn>=0.4.0
  - snowflake-connector-python
