apiVersion: v1
kind: Service
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
  namespace: main-namespace
spec:
  ports:
  - port: 30088
    protocol: TCP
    targetPort: 8888
  selector:
    run: mock-auth-server
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
  namespace: main-namespace
spec:
  containers:
  - image: andrewelkin/mock-auth-server:test
    imagePullPolicy: IfNotPresent
    name: auth
    ports:
    - containerPort: 8888
      protocol: TCP
  dnsPolicy: ClusterFirst
