apiVersion: v1
kind: Service
metadata:
  labels:
    run: proxy-test
  name: proxy-test
  namespace: main-namespace
spec:
  ports:
  - port: 30080
    protocol: TCP
    targetPort: 8080
  selector:
    run: proxy-test
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: proxy-test
  name: proxy-test
  namespace: main-namespace
spec:
  containers:
  - image: andrewelkin/proxy-server:test
    imagePullPolicy: IfNotPresent
    name: proxy
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
      - name: PROXY_LISTEN_PORT
        value: "8080"
      - name: PROXY_TARGET_URL
        value: "http://andrew-aetest-dask.main-namespace:8787"
      - name: PROXY_FALLBACK_URL
        value: "http://a86e698033dd811eab4a7061f42b0bf8-1742805392.us-east-2.elb.amazonaws.com:30088/"
      - name: PROXY_DEBUG
        value: "true"
  dnsPolicy: ClusterFirst

