apiVersion: v1
kind: Service
metadata:
  labels:
    run: proxy-test
  name: proxy-test
  namespace: main-namespace
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30787
  selector:
    run: proxy-test
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: proxy-test
  name: proxy-test
  namespace: main-namespace
spec:
  containers:
  - image: andrewelkin/proxy-server:test
    imagePullPolicy: IfNotPresent
    name: proxy
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
      - name: HTTPS_SELF_REDIRECT
        value: "false"
      - name: PROXY_LISTEN_PORT
        value: "8080"
      - name: PROXY_FALLBACK_URL
        value: "http://mock-auth.test:80/"
      - name: PROXY_DEBUG
        value: "true"
      - name: PROXY_SUFFIX
        value: ".localtest.me"
      - name: PROXY_CONFIG
        value: "/etc/config/proxy.json"
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: proxy-test-config
  dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-test-config
  namespace: main-namespace
data:
  proxy.json: |
    {
    "andrewdask":"http://admin-andrewdask-dask.main-namespace:8787",
    "web":"http://web-resource.default.svc.cluster.local:80"
    }

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
  namespace: main-namespace
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: mock-auth-server
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mock-auth-server
  namespace: main-namespace
spec:
  rules:
    - host: mock-auth.test
      http:
        paths:
        - backend:
            serviceName: mock-auth-server
            servicePort: 8888
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
  namespace: main-namespace
spec:
  containers:
  - image: andrewelkin/mock-auth-server:test
    imagePullPolicy: IfNotPresent
    name: auth
    ports:
    - containerPort: 8888
      protocol: TCP
  dnsPolicy: ClusterFirst
