apiVersion: v1
kind: Service
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: mock-auth-server
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
spec:
  containers:
  - image: mock-auth-server:test
    imagePullPolicy: IfNotPresent
    name: auth
    ports:
    - containerPort: 8888
      protocol: TCP
  dnsPolicy: ClusterFirst
