name: saturn
channels:
    - pytorch
    - rapidsai
    - nvidia
    - nodefaults
    - conda-forge
dependencies:
    - blas=2.114=mkl
    - bokeh
    - pytorch-cuda=12.1
    - dask-cuda
    - dask
    - fastai
    - fsspec
    - ipykernel
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - pillow
    - pip
    - py-opencv
    - pyarrow
    - python-graphviz
    - python
    - pytorch=2.1.0
    - s3fs
    - setuptools
    - tensorboard
    - torchaudio
    - torchvision
    - pynvml
    - pip:
          - dask-saturn>=0.4.1
          - prefect-saturn>=0.6.0
          - snowflake-connector-python==2.7.7
