name: saturn
channels:
    - pytorch
    - rapidsai
    - nvidia
    - nodefaults
    - conda-forge
dependencies:
    - blas=*=mkl
    - bokeh
    - pytorch-cuda=12.1
    - dask-cuda
    - dask
    - fastai
    - fsspec
    - ipykernel
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - pillow
    - pip
    - py-opencv
    - pyarrow
    - python-graphviz
    - python
    - pytorch=2.4.0
    - s3fs
    - setuptools
    - tensorboard
    - torchaudio
    - torchvision
    - pynvml
    - pip:
          - dask-saturn
          - saturn-client
          - saturnfs
          - snowflake-connector-python
