name: saturn
channels:
    - pytorch
    - fastai
    - rapidsai
    - nodefaults
    - conda-forge
dependencies:
    - blas=*=mkl
    - bokeh
    - cudatoolkit=11.3
    - dask
    - dask-cuda=22.04
    - fastai
    - fsspec>=0.8.5
    - ipykernel
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - pillow
    - pip
    - prefect
    - py-opencv
    - pyarrow<6.1.0,>=6.0.0
    - python=3.9
    - python-graphviz
    - pytorch
    - s3fs>=2021.08.0
    - setuptools<60.0
    - tensorboard
    - torchvision
    - torchaudio
    - pip:
          - dask-saturn>=0.4.1
          - prefect-saturn>=0.6.0
          - snowflake-connector-python
