name: saturn
channels:
    - conda-forge
    - nodefaults
dependencies:
    - python=3.13
    - blas=*=mkl
    - bokeh
    - dask
    - fastai
    - fsspec
    - ipykernel
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - pillow
    - pip
    - py-opencv
    - pyarrow
    - python-graphviz
    - s3fs
    - setuptools
    - tensorboard
    - pynvml
    - pip:
          - --extra-index-url https://download.pytorch.org/whl/cu129
          - torch
          - torchvision
          - torchaudio
          - dask-saturn
          - saturn-client
          - saturnfs
          - snowflake-connector-python
