name: saturn
channels:
- defaults
- conda-forge
- rapidsai
dependencies:
- blas=*=mkl
- bokeh
- dask=2.30.0
- dask-cuda=0.17.*
- distributed=2.30.1
- fsspec>=0.8.5
- ipykernel
- ipywidgets
- keras
- matplotlib
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- python-graphviz
- s3fs
- tensorboard=2.2.1
- tensorflow-estimator=2.2.0
- tensorflow=2.2.0=gpu_py37h1a511ff_0
- voila
- pip:
  - dask-saturn>=0.2.3
  - prefect-saturn>=0.5.0
  - snowflake-connector-python
