name: saturn
channels:
- defaults
- conda-forge
- saturncloud
dependencies:
- blas=*=mkl
- bokeh
- dask-saturn
- dask
- distributed
- matplotlib
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- s3fs
- voila
- ipykernel
- ipywidgets
- tensorboard=2.2.1
- tensorflow-base=2.2.0=gpu_py37h8a81be8_0
- tensorflow-estimator=2.2.0
- tensorflow=2.2.0=gpu_py37h1a511ff_0
- pip:
  - snowflake-connector-python
  - prefect-saturn
