name: saturn
channels:
- defaults
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- dask=2.30.0
- distributed=2.30.1
- ipykernel
- ipywidgets
- matplotlib
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- s3fs
- tensorboard=2.2.1
- tensorflow-estimator=2.2.0
- tensorflow==2.2.0=gpu_py37h1a511ff_0
- voila
- pip:
  - dask-saturn>=0.2.2
  - prefect-saturn>=0.4.0
  - snowflake-connector-python
