name: saturn
channels:
- conda-forge
- defaults
- rapidsai
dependencies:
- blas=*=mkl
- bokeh
- dask
- dask-cuda==21.8
- fsspec
- ipykernel
- ipywidgets
- keras
- matplotlib
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.9
- python-graphviz
- s3fs
- setuptools<60.0
- tensorboard
- tensorflow-estimator
- tensorflow=2.4.1=gpu_py39h8236f22_0
- voila
- pip:
  - dask-saturn>=0.4.0
  - prefect-saturn>=0.5.1
  - snowflake-connector-python
