name: saturn
channels:
- conda-forge
- defaults
- rapidsai
dependencies:
- blas=2.114=mkl
- bokeh=2.4.2
- dask=2021.7.1
- dask-cuda==21.8
- fsspec=2022.3.0
- ipykernel=6.13.0
- ipywidgets=7.7.0
- keras=2.4.3
- matplotlib=3.5.1
- numpy=1.22.3
- pandas=1.4.2
- pip=22.0.4
- prefect=0.15.13
- pyarrow<6.1.0,>=6.0.0
- python=3.9
- python-graphviz=0.20
- s3fs=2022.3.0
- setuptools<60.0
- tensorboard=2.8.0
- tensorflow-estimator=2.6.0
- tensorflow=2.4.1=gpu_py39h8236f22_0
- voila=0.3.5
- pip:
  - dask-saturn>=0.4.1
  - prefect-saturn>=0.6.0
  - snowflake-connector-python==2.7.6
