name: saturn
channels:
- defaults
- conda-forge
- rapidsai
dependencies:
- blas=1.0=mkl
- bokeh=2.4.2
- click>=7.1.2,<8.0.5
- dask=2021.07
- distributed=2021.07
- dask-cuda==21.8
- fsspec=2021.10.1
- ipykernel=6.4.1
- ipywidgets=7.6.5
- keras=2.4.3
- matplotlib=3.5.0
- numpy=1.21.2
- pandas=1.3.5
- pip=21.2.4
- prefect=0.15.12
- pyarrow=4.0.1
- python=3.9.7
- python-graphviz=0.16
- s3fs=0.6.0
- setuptools<60.0
- tensorboard
- tensorflow-estimator=2.6.0
- tensorflow=2.4.1=gpu_py39h8236f22_0
- voila=0.3.0
- pip:
  - dask-saturn>=0.4.0
  - prefect-saturn>=0.5.1
  - snowflake-connector-python==2.7.2
