name: saturn
channels:
- defaults
- conda-forge
- rapidsai
dependencies:
- blas=*=mkl
- bokeh
- dask=2021.4.0
- distributed=2021.4.0
- dask-cuda=0.19
- fsspec
- ipykernel
- ipywidgets
- keras
- matplotlib
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.9
- python-graphviz
- s3fs
- tensorboard
- tensorflow-estimator
- tensorflow=2.4.1=gpu_py39h8236f22_0
- voila
- pip:
  - dask-saturn>=0.2.3
  - prefect-saturn>=0.5.0
  - snowflake-connector-python
