name: saturn
channels:
- conda-forge
- defaults
- rapidsai
dependencies:
- blas=1.0=mkl
- bokeh=2.4.2
- click>=7.1.2,<8.0.5
- dask=2021.7.0
- dask-cuda=21.8
- fsspec=2022.1.0
- ipykernel=6.4.1
- ipywidgets=7.6.5
- keras=2.4.3
- matplotlib=3.5.1
- numpy=1.21.2
- pandas=1.4.1
- pip=21.2.4
- prefect=0.15.13
- pyarrow<6.1.0,>=6.0.0
- python=3.9.7
- python-graphviz=0.16
- s3fs=2022.1.0
- setuptools<60.0
- tensorboard=2.6.0
- tensorflow-estimator=2.6.0
- tensorflow=2.4.1=gpu_py39h8236f22_0
- voila=0.3.2
- pip:
  - dask-saturn>=0.4.1
  - prefect-saturn>=0.6.0
  - snowflake-connector-python==2.7.4
