name: saturn
channels:
- https://conda.saturncloud.io/pkgs
- defaults
- conda-forge
- saturncloud
dependencies:
- blas=*=mkl
- bokeh
- dask-saturn
- dask=2.30.0
- distributed=2.30.0
- ipykernel
- ipywidgets
- matplotlib
- numba=0.49.1
- numpy
- pandas
- pip
- prefect
- pyarrow
- python=3.7
- s3fs
- scikit-learn
- scipy
- snowflake-connector-python
- snowflake-sqlalchemy
- tensorboard=2.2.1
- tensorflow-base=2.2.0=gpu_py37h8a81be8_0
- tensorflow-estimator=2.2.0
- tensorflow=2.2.0=gpu_py37h1a511ff_0
- torchvision=0.5.0=py37_cu101
- voila
- wordcloud
- xgboost
