name: saturn
channels:
- nodefaults
- conda-forge
dependencies:
- blas=*=mkl
- bokeh
- cartopy
- dask-ml
- dask
- datashader
- descartes
- distributed
- geopandas
- geoviews
- hvplot
- ipykernel
- ipywidgets
- iris
- matplotlib
- netcdf4
- numpy
- pandas
- pip
- prefect
- pyarrow<6.1.0,>=6.0.0
- python=3.8
- python-graphviz
- rasterio
- s3fs
- scipy
- setuptools<60.0
- voila
- xarray
- zarr
- pip:
  - dask-saturn>=0.4.1
  - prefect-saturn>=0.6.0
  - snowflake-connector-python
