name: Linting

on:
  push:
  schedule:
    # Run every Monday morning at 11:00a UTC, 6:00a CST
    - cron: '0 11 * * 1'

jobs:
  test:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: linting
        if: matrix.task == 'linting'
        shell: bash
        run: |
          pip install --upgrade black flake8 mypy
          make lint
